/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as ProfileAccountIdImport } from './routes/profile/$accountId'
import { Route as LayoutInventoryImport } from './routes/_layout/inventory'
import { Route as LayoutInventoryIndexImport } from './routes/_layout/inventory/index'
import { Route as LayoutlandingIndexImport } from './routes/_layout/(landing)/index'
import { Route as LayoutInventoryInventoryIdImport } from './routes/_layout/inventory/$inventoryId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const ProfileAccountIdRoute = ProfileAccountIdImport.update({
  id: '/profile/$accountId',
  path: '/profile/$accountId',
  getParentRoute: () => rootRoute,
} as any)

const LayoutInventoryRoute = LayoutInventoryImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutInventoryIndexRoute = LayoutInventoryIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutInventoryRoute,
} as any)

const LayoutlandingIndexRoute = LayoutlandingIndexImport.update({
  id: '/(landing)/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutInventoryInventoryIdRoute = LayoutInventoryInventoryIdImport.update(
  {
    id: '/$inventoryId',
    path: '/$inventoryId',
    getParentRoute: () => LayoutInventoryRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/inventory': {
      id: '/_layout/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof LayoutInventoryImport
      parentRoute: typeof LayoutImport
    }
    '/profile/$accountId': {
      id: '/profile/$accountId'
      path: '/profile/$accountId'
      fullPath: '/profile/$accountId'
      preLoaderRoute: typeof ProfileAccountIdImport
      parentRoute: typeof rootRoute
    }
    '/_layout/inventory/$inventoryId': {
      id: '/_layout/inventory/$inventoryId'
      path: '/$inventoryId'
      fullPath: '/inventory/$inventoryId'
      preLoaderRoute: typeof LayoutInventoryInventoryIdImport
      parentRoute: typeof LayoutInventoryImport
    }
    '/_layout/(landing)/': {
      id: '/_layout/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutlandingIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/inventory/': {
      id: '/_layout/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof LayoutInventoryIndexImport
      parentRoute: typeof LayoutInventoryImport
    }
  }
}

// Create and export the route tree

interface LayoutInventoryRouteChildren {
  LayoutInventoryInventoryIdRoute: typeof LayoutInventoryInventoryIdRoute
  LayoutInventoryIndexRoute: typeof LayoutInventoryIndexRoute
}

const LayoutInventoryRouteChildren: LayoutInventoryRouteChildren = {
  LayoutInventoryInventoryIdRoute: LayoutInventoryInventoryIdRoute,
  LayoutInventoryIndexRoute: LayoutInventoryIndexRoute,
}

const LayoutInventoryRouteWithChildren = LayoutInventoryRoute._addFileChildren(
  LayoutInventoryRouteChildren,
)

interface LayoutRouteChildren {
  LayoutInventoryRoute: typeof LayoutInventoryRouteWithChildren
  LayoutlandingIndexRoute: typeof LayoutlandingIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutInventoryRoute: LayoutInventoryRouteWithChildren,
  LayoutlandingIndexRoute: LayoutlandingIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/inventory': typeof LayoutInventoryRouteWithChildren
  '/profile/$accountId': typeof ProfileAccountIdRoute
  '/inventory/$inventoryId': typeof LayoutInventoryInventoryIdRoute
  '/': typeof LayoutlandingIndexRoute
  '/inventory/': typeof LayoutInventoryIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile/$accountId': typeof ProfileAccountIdRoute
  '/inventory/$inventoryId': typeof LayoutInventoryInventoryIdRoute
  '/': typeof LayoutlandingIndexRoute
  '/inventory': typeof LayoutInventoryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/inventory': typeof LayoutInventoryRouteWithChildren
  '/profile/$accountId': typeof ProfileAccountIdRoute
  '/_layout/inventory/$inventoryId': typeof LayoutInventoryInventoryIdRoute
  '/_layout/(landing)/': typeof LayoutlandingIndexRoute
  '/_layout/inventory/': typeof LayoutInventoryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/inventory'
    | '/profile/$accountId'
    | '/inventory/$inventoryId'
    | '/'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile/$accountId'
    | '/inventory/$inventoryId'
    | '/'
    | '/inventory'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/inventory'
    | '/profile/$accountId'
    | '/_layout/inventory/$inventoryId'
    | '/_layout/(landing)/'
    | '/_layout/inventory/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileAccountIdRoute: typeof ProfileAccountIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileAccountIdRoute: ProfileAccountIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/login",
        "/profile/$accountId"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/inventory",
        "/_layout/(landing)/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/inventory": {
      "filePath": "_layout/inventory.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/inventory/$inventoryId",
        "/_layout/inventory/"
      ]
    },
    "/profile/$accountId": {
      "filePath": "profile/$accountId.tsx"
    },
    "/_layout/inventory/$inventoryId": {
      "filePath": "_layout/inventory/$inventoryId.tsx",
      "parent": "/_layout/inventory"
    },
    "/_layout/(landing)/": {
      "filePath": "_layout/(landing)/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/inventory/": {
      "filePath": "_layout/inventory/index.tsx",
      "parent": "/_layout/inventory"
    }
  }
}
ROUTE_MANIFEST_END */
